### ISSUE TITLE
removeEventListener should get callback

### ISSUE THREAD

**Issue by StanislavMayorov** [wowmaking/hybro#1]
Hi. Please update removeEventListener to get callback instead of callbackId.
`export const removeEventListener = function (pckg, mdl, evnt, cbId) `

**Comment by kurtsergey** [comment]
@qvick1pro Do we have some reason to use here callbackId?

**Comment by qvick1pro** [comment]
@kurtsergey Yes, we can't pass handler by JSON messages, we need some kind of IDs to link handlers on native and web sides.
We can only map handler and generated IDs on both sides (web/native) and then remove listeners by passing handler.

**Comment by StanislavMayorov** [comment]
I think we should save IDs inside if they are necessary.
